#!/bin/bash

# Script de déploiement pour le backend CRUD avec variables d'environnement
# Usage: ./deploy.sh [environment] [version]

set -e

# Variables par défaut
ENVIRONMENT=${1:-"production"}
VERSION=${2:-"$(date +%Y%m%d-%H%M%S)"}
INSTANCE_ID=${INSTANCE_ID:-"$(hostname)"}
DEPLOYMENT_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

echo "=========================================="
echo "🚀 Déploiement du Backend CRUD"
echo "=========================================="
echo "📱 Environnement: $ENVIRONMENT"
echo "📦 Version: $VERSION"
echo "🆔 Instance: $INSTANCE_ID"
echo "📅 Date: $DEPLOYMENT_DATE"
echo "=========================================="

# Fonction pour exporter les variables d'environnement
setup_environment() {
    echo "📝 Configuration des variables d'environnement..."
    
    # Variables de base
    export NODE_ENV="$ENVIRONMENT"
    export DEPLOYMENT_VERSION="$VERSION"
    export DEPLOYMENT_DATE="$DEPLOYMENT_DATE"
    export INSTANCE_ID="$INSTANCE_ID"
    export ENVIRONMENT="$ENVIRONMENT"
    
    # Variables spécifiques à l'environnement
    case $ENVIRONMENT in
        "production")
            export PORT=${PORT:-3001}
            export HOST=${HOST:-"0.0.0.0"}
            export LOG_LEVEL=${LOG_LEVEL:-"warn"}
            export ENABLE_CORS=${ENABLE_CORS:-"true"}
            export CORS_ORIGINS=${CORS_ORIGINS:-"*"}
            export DB_POOL_MAX=${DB_POOL_MAX:-20}
            export ENABLE_RATE_LIMIT=${ENABLE_RATE_LIMIT:-"true"}
            export RATE_LIMIT_MAX=${RATE_LIMIT_MAX:-100}
            ;;
        "staging")
            export PORT=${PORT:-3001}
            export HOST=${HOST:-"0.0.0.0"}
            export LOG_LEVEL=${LOG_LEVEL:-"info"}
            export ENABLE_CORS=${ENABLE_CORS:-"true"}
            export DB_POOL_MAX=${DB_POOL_MAX:-10}
            ;;
        "development")
            export PORT=${PORT:-3001}
            export HOST=${HOST:-"localhost"}
            export LOG_LEVEL=${LOG_LEVEL:-"debug"}
            export ENABLE_CORS=${ENABLE_CORS:-"true"}
            export CORS_ORIGINS=${CORS_ORIGINS:-"*"}
            export DB_POOL_MAX=${DB_POOL_MAX:-5}
            ;;
        *)
            echo "❌ Environnement non supporté: $ENVIRONMENT"
            exit 1
            ;;
    esac
    
    echo "✅ Variables d'environnement configurées"
}

# Fonction pour installer les dépendances
install_dependencies() {
    echo "📦 Installation des dépendances..."
    npm ci --only=production
    echo "✅ Dépendances installées"
}

# Fonction pour valider la configuration
validate_config() {
    echo "🔍 Validation de la configuration..."
    
    if [ -z "$DATABASE_URL" ]; then
        echo "❌ DATABASE_URL est requis"
        exit 1
    fi
    
    echo "✅ Configuration validée"
}

# Fonction pour tester la connexion à la base de données
test_database() {
    echo "🗄️  Test de connexion à la base de données..."
    
    # Créer un script de test temporaire
    cat > test_db.js << 'EOF'
const { config, validateConfig } = require('./config');
const { testConnection } = require('./database');

async function test() {
    try {
        validateConfig();
        const result = await testConnection();
        if (result.success) {
            console.log('✅ Connexion à la base de données réussie');
            process.exit(0);
        } else {
            console.error('❌ Échec de la connexion:', result.error);
            process.exit(1);
        }
    } catch (error) {
        console.error('❌ Erreur de test:', error.message);
        process.exit(1);
    }
}

test();
EOF
    
    node test_db.js
    rm test_db.js
    
    echo "✅ Base de données accessible"
}

# Fonction pour démarrer l'application
start_application() {
    echo "🚀 Démarrage de l'application..."
    
    if [ "$ENVIRONMENT" = "production" ]; then
        # En production, utiliser PM2 ou un process manager
        if command -v pm2 &> /dev/null; then
            pm2 start index.js --name "crud-backend-$VERSION" --env $ENVIRONMENT
        else
            # Fallback vers node en mode production
            NODE_ENV=$ENVIRONMENT node index.js
        fi
    else
        # En développement/staging
        npm start
    fi
}

# Fonction pour créer un fichier .env avec les variables actuelles
create_env_file() {
    echo "📝 Création du fichier .env..."
    
    cat > .env << EOF
# Generated by deploy.sh on $DEPLOYMENT_DATE
NODE_ENV=$NODE_ENV
PORT=$PORT
HOST=$HOST
DATABASE_URL=$DATABASE_URL
LOG_LEVEL=$LOG_LEVEL
ENABLE_CORS=$ENABLE_CORS
CORS_ORIGINS=$CORS_ORIGINS
DB_POOL_MAX=$DB_POOL_MAX
DEPLOYMENT_VERSION=$DEPLOYMENT_VERSION
DEPLOYMENT_DATE=$DEPLOYMENT_DATE
INSTANCE_ID=$INSTANCE_ID
ENVIRONMENT=$ENVIRONMENT
EOF
    
    echo "✅ Fichier .env créé"
}

# Fonction principale
main() {
    echo "🏁 Début du déploiement..."
    
    setup_environment
    validate_config
    install_dependencies
    create_env_file
    test_database
    
    echo "=========================================="
    echo "✅ Déploiement prêt!"
    echo "=========================================="
    echo "Pour démarrer l'application:"
    echo "  npm start"
    echo ""
    echo "Ou pour démarrer avec les variables d'environnement:"
    echo "  NODE_ENV=$ENVIRONMENT DEPLOYMENT_VERSION=$VERSION node index.js"
    echo "=========================================="
}

# Vérifier si le script est appelé directement
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi